# UserPreference

###
# @name get_csrf
GET {{endpoint}}/user/csrf/

###
# @name login
POST {{endpoint}}/user/login/
Content-Type: application/json
X-CSRFToken: {{get_csrf.response.headers.X-CSRFToken}}

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###
# @name create
POST {{endpoint}}/api/user_preferences/
Content-Type: application/json
X-CSRFToken: {{get_csrf.response.headers.X-CSRFToken}}

{
  "user_preference": {
    "drink_whens": [
      "デイリー",
      "そのうち",
      "数年寝かす",
      "10年弱寝かす",
      "10年強寝かす",
      "たくさん寝かす"
    ]
  }
}


###
# @name list
GET {{endpoint}}/api/user_preferences/


