# Wine

###
# @name get_csrf
GET {{endpoint}}/user/csrf/

###
# @name login
POST {{endpoint}}/user/login/
Content-Type: application/json
X-CSRFToken: {{get_csrf.response.headers.X-CSRFToken}}

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###
# @name list_all
GET {{endpoint}}/api/wines/

###
# @name list_cellar
GET {{endpoint}}/api/wines/?cellar_id=aa38eecc-7e8d-42c0-90a0-ad39ba584734

###
# @name list_is_drunk
GET {{endpoint}}/api/wines/?is_drunk=true

###
# @name list_only_out_of_cellars
GET {{endpoint}}/api/wines/?out_of_cellars=true

###
# @name create
POST {{endpoint}}/api/wines/
Content-Type: application/json
X-CSRFToken: {{get_csrf.response.headers.X-CSRFToken}}

{
    "name": "Gevrey Chambertin",
    "producer": "Domaine Charlopin Tissier",
    "country": "France",
    "region_1": "Bourgogne",
    "region_2": "Côtes de Nuits",
    "region_3": "Gevrey Chambertin",
    "region_4": "",
    "region_5": "",
    "cepages": [{"name": "Pinot Noir", "abbreviation": "PN", "percentage": 100.0}],
    "vintage": 2019,
    "bought_at": "2023-05-07",
    "bought_from": "伊勢屋",
    "price_with_tax": 13000,
    "drunk_at": null,
    "note": "テスト用のノート",
    "tag_texts": []
}

###
@wine_id=cf7718e9-b7d3-404d-bd3c-ca28d1ade76a

###
# @name update
PUT {{endpoint}}/api/wines/{{wine_id}}/
Content-Type: application/json
Accept: application/json
X-CSRFToken: {{get_csrf.response.headers.X-CSRFToken}}

{
  "name": "Le Prince",
  "producer": "Domaine de Roche Ville",
  "country": "France",
  "region_1": "Loire",
  "region_2": "Saumur Champigny",
  "region_3": "",
  "region_4": "",
  "region_5": "",
  "cepages": [
    {
      "name": "Cabernet Franc",
      "abbreviation": "CF",
      "percentage": "100.0"
    }
  ],
  "vintage": 2017,
  "bought_at": "2023-04-18",
  "bought_from": "エノテカオンライン",
  "price_with_tax": 3080,
  "drunk_at": null,
  "note": "",
  "tag_texts": [
    "デイリー"
  ]
}

###
# @name update_with_move
PUT {{endpoint}}/api/wines/{{wine_id}}/
Content-Type: application/json
Accept: application/json
X-CSRFToken: {{get_csrf.response.headers.X-CSRFToken}}

{
  "name": "Le Prince",
  "producer": "Domaine de Roche Ville",
  "country": "France",
  "region_1": "Loire",
  "region_2": "Saumur Champigny",
  "region_3": "",
  "region_4": "",
  "region_5": "",
  "cepages": [
    {
      "name": "Cabernet Franc",
      "abbreviation": "CF",
      "percentage": "100.0"
    }
  ],
  "vintage": 2017,
  "bought_at": "2023-04-18",
  "bought_from": "エノテカオンライン",
  "price_with_tax": 3080,
  "drunk_at": null,
  "note": "",
  "tag_texts": [
    "デイリー"
  ],
  "cellar_id": "aa38eecc-7e8d-42c0-90a0-ad39ba584734",
  "position": "basket"
}
