# WineTag

###
# @name get_csrf
GET {{endpoint}}/user/csrf/

###
# @name login
POST {{endpoint}}/user/login/
Content-Type: application/json
X-CSRFToken: {{get_csrf.response.headers.X-CSRFToken}}

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###
# @name list
GET {{endpoint}}/api/wine_tags/

###
@wine_tag_text = "10年寝かす"

###
# @name delete
DELETE {{endpoint}}/api/wine_tags/
Content-Type: application/json
X-CSRFToken: {{get_csrf.response.headers.X-CSRFToken}}

{
  "tag_text": {{wine_tag_text}}
}
