# Generated by Django 4.1.1 on 2023-05-03 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drink_when", models.TextField(blank=True, default="")),
                ("name", models.CharField(blank=True, default="", max_length=256)),
                ("producer", models.CharField(blank=True, default="", max_length=128)),
                (
                    "country",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (101, "France"),
                            (102, "Italy"),
                            (103, "Germany"),
                            (104, "Luxembourg"),
                            (105, "Spain"),
                            (106, "Portugal"),
                            (107, "Switzerland"),
                            (108, "Austria"),
                            (109, "England"),
                            (200, "Hungary"),
                            (201, "Bulgaria"),
                            (202, "Slovenia"),
                            (203, "Croatia"),
                            (204, "Bosnia Herzegovina"),
                            (205, "Macedonia"),
                            (206, "Serbia"),
                            (207, "Montenegro"),
                            (208, "Czech Republic"),
                            (209, "Slovak Republic"),
                            (210, "Romania"),
                            (211, "Malta"),
                            (212, "Greece"),
                            (301, "Japan"),
                            (302, "Armenia"),
                            (303, "Georgia"),
                            (304, "Moldova"),
                            (305, "Russia"),
                            (306, "Ukraine"),
                            (401, "America"),
                            (402, "Mexico"),
                            (403, "Canada"),
                            (404, "Chile"),
                            (405, "Argentina"),
                            (406, "Brazil"),
                            (407, "Uruguay"),
                            (501, "Australia"),
                            (502, "New Zealand"),
                            (601, "Cyprus"),
                            (602, "Israel"),
                            (603, "Lebanon"),
                            (604, "Turkey"),
                            (605, "North Africa"),
                            (606, "South Africa"),
                        ],
                        null=True,
                    ),
                ),
                ("region_1", models.CharField(blank=True, default="", max_length=128)),
                ("region_2", models.CharField(blank=True, default="", max_length=128)),
                ("region_3", models.CharField(blank=True, default="", max_length=128)),
                ("region_4", models.CharField(blank=True, default="", max_length=128)),
                ("region_5", models.CharField(blank=True, default="", max_length=128)),
                ("cepage", models.JSONField(blank=True, default=list)),
                ("vintage", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("bought_at", models.DateField(blank=True, null=True)),
                (
                    "bought_from",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("price_with_tax", models.PositiveIntegerField(blank=True, null=True)),
                ("drunk_at", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
