# Generated by Django 4.2.1 on 2023-07-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wines", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wine",
            name="country",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (101, "France"),
                    (102, "Italy"),
                    (103, "Germany"),
                    (104, "Luxembourg"),
                    (105, "Spain"),
                    (106, "Portugal"),
                    (107, "Switzerland"),
                    (108, "Austria"),
                    (109, "England"),
                    (200, "Hungary"),
                    (201, "Bulgaria"),
                    (202, "Slovenia"),
                    (203, "Croatia"),
                    (204, "Bosnia Herzegovina"),
                    (205, "Macedonia"),
                    (206, "Serbia"),
                    (207, "Montenegro"),
                    (208, "Czech Republic"),
                    (209, "Slovak Republic"),
                    (210, "Romania"),
                    (211, "Malta"),
                    (212, "Greece"),
                    (301, "Japan"),
                    (302, "Armenia"),
                    (303, "Georgia"),
                    (304, "Moldova"),
                    (305, "Russia"),
                    (306, "Ukraine"),
                    (401, "America"),
                    (402, "Mexico"),
                    (403, "Canada"),
                    (404, "Chile"),
                    (405, "Argentina"),
                    (406, "Brazil"),
                    (407, "Uruguay"),
                    (501, "Australia"),
                    (502, "New Zealand"),
                    (601, "Cyprus"),
                    (602, "Israel"),
                    (603, "Lebanon"),
                    (604, "Turkey"),
                    (605, "North Africa"),
                    (606, "South Africa"),
                ],
                db_column="country",
                null=True,
            ),
        ),
        migrations.RenameField(
            model_name="wine",
            old_name="country",
            new_name="_country",
        ),
        migrations.AddField(
            model_name="wine",
            name="_country_str",
            field=models.CharField(blank=True, db_column="country_str", max_length=64, null=True),
        ),
    ]
