# Generated by Django 4.2.1 on 2023-08-25 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wines", "0003_winetag_winetagrelation_wine_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wine",
            name="drink_when",
        ),
    ]
