# Generated by Django 4.2.1 on 2023-08-28 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wines", "0004_remove_wine_drink_when"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cepage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("percentage", models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="GrapeMaster",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField()),
                ("abbreviation", models.CharField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="wine",
            name="cepage",
        ),
        migrations.AlterField(
            model_name="winetag",
            name="text",
            field=models.CharField(max_length=256),
        ),
        migrations.AddConstraint(
            model_name="winetag",
            constraint=models.UniqueConstraint(fields=("text", "user"), name="unique_text_user"),
        ),
        migrations.AddField(
            model_name="grapemaster",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="cepage",
            name="grape",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="wines.grapemaster"),
        ),
        migrations.AddField(
            model_name="cepage",
            name="wine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="cepages", to="wines.wine"
            ),
        ),
        migrations.AddConstraint(
            model_name="grapemaster",
            constraint=models.UniqueConstraint(fields=("name", "user"), name="unique_name_user"),
        ),
    ]
