# Generated by Django 4.2.1 on 2023-09-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wines", "0005_cepage_grapemaster_remove_wine_cepage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wine",
            name="name",
            field=models.CharField(max_length=256),
        ),
    ]
