# Generated by Django 4.2.1 on 2023-12-10 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wines", "0007_rename_price_with_tax_wine_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cepage",
            name="grape",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="cepages", to="wines.grapemaster"
            ),
        ),
    ]
