# Generated by Django 4.2.1 on 2024-06-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wines", "0009_auto_20240513_0729"),
    ]

    operations = [
        migrations.AddField(
            model_name="wine",
            name="value",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
