# Generated by Django 4.1.1 on 2023-05-05 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wines", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cellar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("layout", models.JSONField()),
                ("has_basket", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CellarSpace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("row", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("column", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "Rack"), (2, "Basket")], default=1
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cellar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cellars.cellar"
                    ),
                ),
                (
                    "wine",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wines.wine",
                    ),
                ),
            ],
        ),
    ]
