# Generated by Django 4.1.1 on 2023-05-05 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wines", "0001_initial"),
        ("cellars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CellarSpace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("column", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "Rack"), (2, "Basket")], default=1
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cellar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cellars.cellar"
                    ),
                ),
                (
                    "wine",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wines.wine",
                    ),
                ),
            ],
        ),
    ]
