import { fireEvent, render, screen } from '@testing-library/react';
import { rest } from 'msw';
import { setupServer } from 'msw/node';
import App from '../../App';
import { BrowserRouter } from 'react-router-dom';

const server = setupServer(
    rest.get('/user/session/', (req, res, ctx) => {
        return res(ctx.json({ is_authenticated: true }));
    }),
    rest.get('/api/cellars/', (req, res, ctx) => {
        return res(
            ctx.json({
                cellars: [
                    {
                        id: 'cellar00-0000-0000-0000-000000000000',
                        name: 'Forester',
                        layout: [5, 6, 6, 6, 6],
                        has_basket: true,
                    },
                ],
            }),
        );
    }),
    rest.get('/api/wine_tags/', (req, res, ctx) => {
        return res(
            ctx.json({
                tag_texts: ['プレゼント', '00:daily', '01:そのうち', '05:数年', '10-年', '10+年', '20+年', 'no', 'yes', '古すぎた', '次の候補'],
            }),
        );
    }),
    rest.get('/api/wines/', (req, res, ctx) => {
        return res(
            ctx.json({
                wines: [
                    {
                        id: 'wine0000-0000-0000-0000-000000000001',
                        name: 'Elixir',
                        producer: 'Domaine la Condamine Bertrand',
                        country: 'France',
                        region_1: 'Languedoc Roussillon',
                        region_2: "Pays d'Oc",
                        region_3: '',
                        region_4: '',
                        region_5: '',
                        cepages: [
                            {
                                name: 'Syrah',
                                abbreviation: '',
                                percentage: '92.0',
                            },
                            {
                                name: 'Cabernet Sauvignon',
                                abbreviation: 'CS',
                                percentage: '8.0',
                            },
                        ],
                        vintage: 2000,
                        bought_at: '2023-07-09',
                        bought_from: '伊勢屋',
                        price_with_tax: 5500,
                        drunk_at: null,
                        note: '',
                        tag_texts: ['01:そのうち', '次の候補'],
                        cellar_id: 'cellar00-0000-0000-0000-000000000000',
                        position: '1-1',
                    },
                    {
                        id: 'wine0000-0000-0000-0000-000000000020',
                        name: 'Cline Sonoma Coast Syrah',
                        producer: 'Cline Cellars',
                        country: 'America',
                        region_1: 'California',
                        region_2: 'North Coast',
                        region_3: 'Sonoma County',
                        region_4: 'Sonoma Coast',
                        region_5: '',
                        cepages: [
                            {
                                name: 'Syrah',
                                abbreviation: '',
                                percentage: '100.0',
                            },
                        ],
                        vintage: 2019,
                        bought_at: '2023-10-30',
                        bought_from: '今井商店',
                        price_with_tax: 2277,
                        drunk_at: null,
                        note: '',
                        tag_texts: ['01:そのうち'],
                        cellar_id: 'cellar00-0000-0000-0000-000000000000',
                        position: '1-2',
                    },
                    {
                        id: 'wine0000-0000-0000-0000-000000000021',
                        name: 'D2',
                        producer: 'DeLille Cellars',
                        country: 'America',
                        region_1: 'Washington',
                        region_2: 'Columbia Valley',
                        region_3: '',
                        region_4: '',
                        region_5: '',
                        cepages: [
                            {
                                name: 'Merlot',
                                abbreviation: 'Mr',
                                percentage: '60.0',
                            },
                            {
                                name: 'Cabernet Sauvignon',
                                abbreviation: 'CS',
                                percentage: '34.0',
                            },
                            {
                                name: 'Cabernet Franc',
                                abbreviation: 'CF',
                                percentage: '4.0',
                            },
                            {
                                name: 'Petit Verdot',
                                abbreviation: 'PV',
                                percentage: '2.0',
                            },
                        ],
                        vintage: 2019,
                        bought_at: '2023-10-30',
                        bought_from: '今井商店',
                        price_with_tax: 7304,
                        drunk_at: null,
                        note: '',
                        tag_texts: ['01:そのうち'],
                        cellar_id: 'cellar00-0000-0000-0000-000000000000',
                        position: '1-3',
                    },
                    {
                        id: 'wine0000-0000-0000-0000-000000000022',
                        name: 'Pinot Noir Carneros',
                        producer: 'Clos du Val',
                        country: 'America',
                        region_1: 'California',
                        region_2: 'North Coast',
                        region_3: 'Napa County',
                        region_4: 'Napa Valley',
                        region_5: 'Carneros',
                        cepages: [
                            {
                                name: 'Pinot Noir',
                                abbreviation: 'PN',
                                percentage: '100.0',
                            },
                        ],
                        vintage: 2018,
                        bought_at: '2023-10-30',
                        bought_from: '今井商店',
                        price_with_tax: 6237,
                        drunk_at: null,
                        note: '',
                        tag_texts: ['01:そのうち'],
                        cellar_id: 'cellar00-0000-0000-0000-000000000000',
                        position: '1-4',
                    },
                    {
                        id: 'wine0000-0000-0000-0000-000000000006',
                        name: 'Bourgogne',
                        producer: 'Méo Camuzet',
                        country: 'France',
                        region_1: 'Bourgogne',
                        region_2: '',
                        region_3: '',
                        region_4: '',
                        region_5: '',
                        cepages: [
                            {
                                name: 'Pinot Noir',
                                abbreviation: 'PN',
                                percentage: '100.0',
                            },
                        ],
                        vintage: null,
                        bought_at: '2022-07-31',
                        bought_from: '伊勢屋',
                        price_with_tax: 7150,
                        drunk_at: null,
                        note: '',
                        tag_texts: ['05:数年', '次の候補'],
                        cellar_id: 'cellar00-0000-0000-0000-000000000000',
                        position: '1-5',
                    },
                    {
                        id: 'wine0000-0000-0000-0000-000000000014',
                        name: 'Gevrey Chambertin 1er Cru Les Cazetiers',
                        producer: 'Lucien le Moine',
                        country: 'France',
                        region_1: 'Bourgogne',
                        region_2: 'Côtes de Nuits',
                        region_3: 'Gevrey Chambertin',
                        region_4: 'Les Cazetiers',
                        region_5: '',
                        cepages: [
                            {
                                name: 'Pinot Noir',
                                abbreviation: 'PN',
                                percentage: '100.0',
                            },
                        ],
                        vintage: 2014,
                        bought_at: '2019-06-15',
                        bought_from: '勝田商店',
                        price_with_tax: 18630,
                        drunk_at: null,
                        note: '澱はなく、色は少し薄め。透明度は高め 2020/8/23微細な澱がわずかにある。ベルタンらしい褐色が微かに感じられる。',
                        tag_texts: ['20+年'],
                        cellar_id: 'cellar00-0000-0000-0000-000000000000',
                        position: '2-1',
                    },
                    {
                        id: 'wine0000-0000-0000-0000-000000000023',
                        name: '',
                        producer: '',
                        country: null,
                        region_1: '',
                        region_2: '',
                        region_3: '',
                        region_4: '',
                        region_5: '',
                        cepages: [],
                        vintage: null,
                        bought_at: null,
                        bought_from: '',
                        price_with_tax: null,
                        drunk_at: null,
                        note: '',
                        tag_texts: [],
                        cellar_id: 'cellar00-0000-0000-0000-000000000000',
                        position: '2-2',
                    },
                    {
                        id: 'wine0000-0000-0000-0000-000000000002',
                        name: 'Corbières',
                        producer: 'Via Nostrum',
                        country: 'France',
                        region_1: 'Languedoc',
                        region_2: 'Corbières',
                        region_3: '',
                        region_4: '',
                        region_5: '',
                        cepages: [
                            {
                                name: 'Syrah',
                                abbreviation: '',
                                percentage: '70.0',
                            },
                            {
                                name: 'Grenache',
                                abbreviation: '',
                                percentage: '30.0',
                            },
                        ],
                        vintage: 2018,
                        bought_at: '2023-02-05',
                        bought_from: '伊勢屋',
                        price_with_tax: 1540,
                        drunk_at: null,
                        note: '',
                        tag_texts: ['00:daily'],
                        cellar_id: 'cellar00-0000-0000-0000-000000000000',
                        position: '2-3',
                    },
                    {
                        id: 'wine0000-0000-0000-0000-000000000003',
                        name: "Sarah's Vineyard Pinot Noir",
                        producer: "Sarah's Vineyard",
                        country: 'America',
                        region_1: 'California',
                        region_2: 'Central Coast',
                        region_3: 'Santa Clara',
                        region_4: '',
                        region_5: '',
                        cepages: [
                            {
                                name: 'Pinot Noir',
                                abbreviation: 'PN',
                                percentage: '100.0',
                            },
                        ],
                        vintage: 2017,
                        bought_at: '2023-08-27',
                        bought_from: '伊勢屋',
                        price_with_tax: 2750,
                        drunk_at: null,
                        note: '',
                        tag_texts: ['01:そのうち', '次の候補'],
                        cellar_id: 'cellar00-0000-0000-0000-000000000000',
                        position: '2-4',
                    },
                    {
                        id: 'wine0000-0000-0000-0000-000000000013',
                        name: 'Gevrey Chambertin Lavaux St Jacques 1er',
                        producer: 'Claude Dugat',
                        country: 'France',
                        region_1: 'Bourgogne',
                        region_2: 'Côtes de Nuits',
                        region_3: 'Gevrey Chambertin',
                        region_4: 'Lavaux st Jacques',
                        region_5: '',
                        cepages: [
                            {
                                name: 'Pinot Noir',
                                abbreviation: 'PN',
                                percentage: '100.0',
                            },
                        ],
                        vintage: 2016,
                        bought_at: '2019-06-15',
                        bought_from: '勝田商店',
                        price_with_tax: 30780,
                        drunk_at: null,
                        note: '澱はなく、色はどちらかというと濃いめ。長期熟成が期待できそう。よく透き通っている。',
                        tag_texts: ['20+年'],
                        cellar_id: 'cellar00-0000-0000-0000-000000000000',
                        position: '2-5',
                    },
                    {
                        id: 'wine0000-0000-0000-0000-000000000008',
                        name: 'Chablis Grand Cru Valmur',
                        producer: 'Maison du Tastelune',
                        country: 'France',
                        region_1: 'Bourgogne',
                        region_2: 'Chablis',
                        region_3: 'Valmur',
                        region_4: '',
                        region_5: '',
                        cepages: [
                            {
                                name: 'Chardonnay',
                                abbreviation: 'Ch',
                                percentage: '100.0',
                            },
                        ],
                        vintage: 2014,
                        bought_at: '2020-04-07',
                        bought_from: '天満屋 頒布会',
                        price_with_tax: 10000,
                        drunk_at: null,
                        note: '澱なし',
                        tag_texts: ['10-年'],
                        cellar_id: 'cellar00-0000-0000-0000-000000000000',
                        position: '2-6',
                    },
                    {
                        id: 'wine0000-0000-0000-0000-000000000024',
                        name: '',
                        producer: '',
                        country: null,
                        region_1: '',
                        region_2: '',
                        region_3: '',
                        region_4: '',
                        region_5: '',
                        cepages: [],
                        vintage: null,
                        bought_at: null,
                        bought_from: '',
                        price_with_tax: null,
                        drunk_at: null,
                        note: '',
                        tag_texts: [],
                        cellar_id: 'cellar00-0000-0000-0000-000000000000',
                        position: '3-1',
                    },
                    {
                        id: 'wine0000-0000-0000-0000-000000000004',
                        name: "Sarah's Vineyard Pinot Noir",
                        producer: "Sarah's Vineyard",
                        country: 'America',
                        region_1: 'California',
                        region_2: 'Central Coast',
                        region_3: 'Santa Clara',
                        region_4: '',
                        region_5: '',
                        cepages: [
                            {
                                name: 'Pinot Noir',
                                abbreviation: 'PN',
                                percentage: '100.0',
                            },
                        ],
                        vintage: 2017,
                        bought_at: '2023-08-27',
                        bought_from: '伊勢屋',
                        price_with_tax: 2750,
                        drunk_at: null,
                        note: '',
                        tag_texts: ['01:そのうち'],
                        cellar_id: 'cellar00-0000-0000-0000-000000000000',
                        position: '3-2',
                    },
                    {
                        id: 'wine0000-0000-0000-0000-000000000007',
                        name: 'Chasse Spleen',
                        producer: 'Château Chasse Spleen',
                        country: 'France',
                        region_1: 'Bordeaux',
                        region_2: 'Médoc',
                        region_3: 'Moulis',
                        region_4: '',
                        region_5: '',
                        cepages: [],
                        vintage: 2013,
                        bought_at: '2019-06-15',
                        bought_from: '天満屋',
                        price_with_tax: 5724,
                        drunk_at: null,
                        note: '澱はなく、色は濃いめで透き通っている。',
                        tag_texts: ['05:数年', '次の候補'],
                        cellar_id: 'cellar00-0000-0000-0000-000000000000',
                        position: '3-3',
                    },
                    {
                        id: 'wine0000-0000-0000-0000-000000000019',
                        name: 'Talbot',
                        producer: 'Château Talbot',
                        country: 'France',
                        region_1: 'Bordeaux',
                        region_2: 'Médoc',
                        region_3: 'Saint-Julien',
                        region_4: '',
                        region_5: '',
                        cepages: [],
                        vintage: 2009,
                        bought_at: '2013-04-03',
                        bought_from: '天満屋(Enoteca)',
                        price_with_tax: 10800,
                        drunk_at: null,
                        note: '"ごく細かな澱がわずか。色はとても赤く綺麗\n2015/3/5細かめの澱が多めに出ていて、瓶にくっついている。澄んでいて状態は期待できそう。"',
                        tag_texts: ['20+年'],
                        cellar_id: 'cellar00-0000-0000-0000-000000000000',
                        position: '3-4',
                    },
                    {
                        id: 'wine0000-0000-0000-0000-000000000010',
                        name: 'Volnay Clos du Château des Ducs',
                        producer: 'Domaine Michel Lafarge',
                        country: 'France',
                        region_1: 'Bourgogne',
                        region_2: 'Côtes de Beaune',
                        region_3: 'Volnay',
                        region_4: 'Clos du Château des Ducs',
                        region_5: '',
                        cepages: [
                            {
                                name: 'Pinot Noir',
                                abbreviation: 'PN',
                                percentage: '100.0',
                            },
                        ],
                        vintage: 2007,
                        bought_at: '2023-06-03',
                        bought_from: '伊勢屋',
                        price_with_tax: 18480,
                        drunk_at: null,
                        note: '店で透かしてみたら、ときめくような色をしていた。そこに細かいけど悪くない澱が小指の爪くらい溜まっている',
                        tag_texts: ['10+年'],
                        cellar_id: 'cellar00-0000-0000-0000-000000000000',
                        position: '3-5',
                    },
                    {
                        id: 'wine0000-0000-0000-0000-000000000005',
                        name: "Sarah's Vineyard Pinot Noir",
                        producer: "Sarah's Vineyard",
                        country: 'America',
                        region_1: 'California',
                        region_2: 'Central Coast',
                        region_3: 'Santa Clara',
                        region_4: '',
                        region_5: '',
                        cepages: [
                            {
                                name: 'Pinot Noir',
                                abbreviation: 'PN',
                                percentage: '100.0',
                            },
                        ],
                        vintage: 2017,
                        bought_at: '2023-08-27',
                        bought_from: '伊勢屋',
                        price_with_tax: 2750,
                        drunk_at: null,
                        note: '',
                        tag_texts: ['01:そのうち'],
                        cellar_id: 'cellar00-0000-0000-0000-000000000000',
                        position: '3-6',
                    },
                    {
                        id: 'wine0000-0000-0000-0000-000000000017',
                        name: 'Chambertin',
                        producer: 'Phillipe Charlopin',
                        country: 'France',
                        region_1: 'Bourgogne',
                        region_2: 'Côtes de Nuits',
                        region_3: 'Gevrey Chambertin',
                        region_4: 'Chambertin',
                        region_5: '',
                        cepages: [
                            {
                                name: 'Pinot Noir',
                                abbreviation: 'PN',
                                percentage: '100.0',
                            },
                        ],
                        vintage: 2012,
                        bought_at: '2016-11-05',
                        bought_from: '安田',
                        price_with_tax: 41040,
                        drunk_at: null,
                        note: '',
                        tag_texts: ['20+年'],
                        cellar_id: 'cellar00-0000-0000-0000-000000000000',
                        position: '4-1',
                    },
                    {
                        id: 'wine0000-0000-0000-0000-000000000025',
                        name: '',
                        producer: '',
                        country: null,
                        region_1: '',
                        region_2: '',
                        region_3: '',
                        region_4: '',
                        region_5: '',
                        cepages: [],
                        vintage: null,
                        bought_at: null,
                        bought_from: '',
                        price_with_tax: null,
                        drunk_at: null,
                        note: '',
                        tag_texts: [],
                        cellar_id: 'cellar00-0000-0000-0000-000000000000',
                        position: '4-2',
                    },
                    {
                        id: 'wine0000-0000-0000-0000-000000000026',
                        name: '',
                        producer: '',
                        country: null,
                        region_1: '',
                        region_2: '',
                        region_3: '',
                        region_4: '',
                        region_5: '',
                        cepages: [],
                        vintage: null,
                        bought_at: null,
                        bought_from: '',
                        price_with_tax: null,
                        drunk_at: null,
                        note: '',
                        tag_texts: [],
                        cellar_id: 'cellar00-0000-0000-0000-000000000000',
                        position: '4-3',
                    },
                    {
                        id: 'wine0000-0000-0000-0000-000000000027',
                        name: '',
                        producer: '',
                        country: null,
                        region_1: '',
                        region_2: '',
                        region_3: '',
                        region_4: '',
                        region_5: '',
                        cepages: [],
                        vintage: null,
                        bought_at: null,
                        bought_from: '',
                        price_with_tax: null,
                        drunk_at: null,
                        note: '',
                        tag_texts: [],
                        cellar_id: 'cellar00-0000-0000-0000-000000000000',
                        position: '4-4',
                    },
                    {
                        id: 'wine0000-0000-0000-0000-000000000012',
                        name: 'Vosne Romanée 1er Cru Les Suchots',
                        producer: 'Lucien le Moine',
                        country: 'France',
                        region_1: 'Bourgogne',
                        region_2: 'Côtes de Nuits',
                        region_3: 'Vosne Romanée',
                        region_4: 'Les Suchots',
                        region_5: '',
                        cepages: [
                            {
                                name: 'Pinot Noir',
                                abbreviation: 'PN',
                                percentage: '100.0',
                            },
                        ],
                        vintage: 2013,
                        bought_at: '2019-06-15',
                        bought_from: '勝田商店',
                        price_with_tax: 24030,
                        drunk_at: null,
                        note: '箔状の少し沈みにくい細かな澱が少し積もっている。色は標準的な濃さで強すぎることもない程よい赤み。どちらかというと軽やかなタイプかも　2020/8/23澱が見当たらない。色はまだ若々しく健康的な濃い赤色',
                        tag_texts: ['20+年'],
                        cellar_id: 'cellar00-0000-0000-0000-000000000000',
                        position: '4-5',
                    },
                    {
                        id: 'wine0000-0000-0000-0000-000000000011',
                        name: 'Dom Pérignon',
                        producer: 'Dom Pérignon',
                        country: 'France',
                        region_1: 'Champagne',
                        region_2: '',
                        region_3: '',
                        region_4: '',
                        region_5: '',
                        cepages: [],
                        vintage: null,
                        bought_at: '2021-11-01',
                        bought_from: '大介内祝',
                        price_with_tax: null,
                        drunk_at: null,
                        note: '',
                        tag_texts: ['10+年'],
                        cellar_id: 'cellar00-0000-0000-0000-000000000000',
                        position: '4-6',
                    },
                    {
                        id: 'wine0000-0000-0000-0000-000000000028',
                        name: '',
                        producer: '',
                        country: null,
                        region_1: '',
                        region_2: '',
                        region_3: '',
                        region_4: '',
                        region_5: '',
                        cepages: [],
                        vintage: null,
                        bought_at: null,
                        bought_from: '',
                        price_with_tax: null,
                        drunk_at: null,
                        note: '',
                        tag_texts: [],
                        cellar_id: 'cellar00-0000-0000-0000-000000000000',
                        position: '5-1',
                    },
                    {
                        id: 'wine0000-0000-0000-0000-000000000009',
                        name: 'Barbaresco Angelo',
                        producer: 'Albino Rocca',
                        country: 'Italy',
                        region_1: 'Piemonte',
                        region_2: 'Cuneo',
                        region_3: 'Barbaresco',
                        region_4: '',
                        region_5: '',
                        cepages: [],
                        vintage: 2014,
                        bought_at: '2023-06-03',
                        bought_from: '伊勢屋',
                        price_with_tax: 13200,
                        drunk_at: null,
                        note: '',
                        tag_texts: ['10-年'],
                        cellar_id: 'cellar00-0000-0000-0000-000000000000',
                        position: '5-2',
                    },
                    {
                        id: 'wine0000-0000-0000-0000-000000000029',
                        name: '',
                        producer: '',
                        country: null,
                        region_1: '',
                        region_2: '',
                        region_3: '',
                        region_4: '',
                        region_5: '',
                        cepages: [],
                        vintage: null,
                        bought_at: null,
                        bought_from: '',
                        price_with_tax: null,
                        drunk_at: null,
                        note: '',
                        tag_texts: [],
                        cellar_id: 'cellar00-0000-0000-0000-000000000000',
                        position: '5-3',
                    },
                    {
                        id: 'wine0000-0000-0000-0000-000000000016',
                        name: 'Corton Bressandes GC',
                        producer: 'Lucien le Moine',
                        country: 'France',
                        region_1: 'Bourgogne',
                        region_2: 'Côtes de Beaune',
                        region_3: 'Corton',
                        region_4: '',
                        region_5: '',
                        cepages: [
                            {
                                name: 'Pinot Noir',
                                abbreviation: 'PN',
                                percentage: '100.0',
                            },
                        ],
                        vintage: 2012,
                        bought_at: '2019-06-15',
                        bought_from: '勝田商店',
                        price_with_tax: 17280,
                        drunk_at: null,
                        note: '綿状の澱僅かにあり、色は微妙に薄め。よく透き通っている。',
                        tag_texts: ['20+年'],
                        cellar_id: 'cellar00-0000-0000-0000-000000000000',
                        position: '5-4',
                    },
                    {
                        id: 'wine0000-0000-0000-0000-000000000015',
                        name: 'Charmes Chambertin',
                        producer: 'Lou Dumont',
                        country: 'France',
                        region_1: 'Bourgogne',
                        region_2: 'Côtes de Nuits',
                        region_3: 'Gevrey Chambertin',
                        region_4: 'Charmes Chambertin',
                        region_5: '',
                        cepages: [
                            {
                                name: 'Pinot Noir',
                                abbreviation: 'PN',
                                percentage: '100.0',
                            },
                        ],
                        vintage: 2016,
                        bought_at: '2020-08-05',
                        bought_from: '天満屋岡山',
                        price_with_tax: 29590,
                        drunk_at: null,
                        note: '',
                        tag_texts: ['20+年'],
                        cellar_id: 'cellar00-0000-0000-0000-000000000000',
                        position: '5-5',
                    },
                    {
                        id: 'wine0000-0000-0000-0000-000000000018',
                        name: 'Clos Vougeot',
                        producer: 'Domaine Louis Jadot',
                        country: 'France',
                        region_1: 'Bourgogne',
                        region_2: 'Côtes de Nuits',
                        region_3: 'Vougeot',
                        region_4: 'Clos Vougeot',
                        region_5: '',
                        cepages: [
                            {
                                name: 'Pinot Noir',
                                abbreviation: 'PN',
                                percentage: '100.0',
                            },
                        ],
                        vintage: 2010,
                        bought_at: '2013-04-03',
                        bought_from: '日本リカー',
                        price_with_tax: 19440,
                        drunk_at: null,
                        note: '20190615よく沈むかなり細かな澱が僅かに出ている。色はまだまだ若々しい赤で、透明度も申し分ない。熟成にはまだまだ長い時間がかかりそう。',
                        tag_texts: ['20+年'],
                        cellar_id: 'cellar00-0000-0000-0000-000000000000',
                        position: '5-6',
                    },
                ],
            }),
        );
    }),
);

beforeAll(() => server.listen());
afterEach(() => server.resetHandlers());
afterAll(() => server.close());

test('WineList page', async () => {
    const { container } = render(<App />, { wrapper: BrowserRouter });

    await fireEvent.click(screen.getByText('Wine List'));
    await screen.findByText('1-1');

    expect(container).toMatchSnapshot();
});
